name: Node CI

on: ['push']

jobs:
  setup:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  quality:
    runs-on: ['ubuntu-latest']
    needs: ['setup']

    steps:
      - uses: actions/checkout@v2

      - name: Run Lint
        run: yarn lint

      - name: Run Test
        run: yarn test
