name: Node CI

on: ['push']

jobs:
  quality:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Run Test
        run: yarn test

  deploy:
    runs-on: ['ubuntu-latest']
    needs: ['quality']
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install Vercel
        run: yarn global add vercel

      - name: Publish
        run: cd public && vercel -c --prod -t ${{secrets.VERCEL_TOKEN}}  deploy ${{secrets.VERCEL_PROJECT_NAME}}
